//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.296
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIExample.SearchManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchMessage", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class SearchMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CriteriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.SearchOptions OptionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Projection {
            get {
                return this.ProjectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectionField, value) != true)) {
                    this.ProjectionField = value;
                    this.RaisePropertyChanged("Projection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Criteria {
            get {
                return this.CriteriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CriteriaField, value) != true)) {
                    this.CriteriaField = value;
                    this.RaisePropertyChanged("Criteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public WIExample.SearchManager.SearchOptions Options {
            get {
                return this.OptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsField, value) != true)) {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchOptions", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class SearchOptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.SearchType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.SearchPaging PagingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.SortDirection SortDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.SearchSorting SortingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WIExample.SearchManager.SearchType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public WIExample.SearchManager.SearchPaging Paging {
            get {
                return this.PagingField;
            }
            set {
                if ((object.ReferenceEquals(this.PagingField, value) != true)) {
                    this.PagingField = value;
                    this.RaisePropertyChanged("Paging");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public WIExample.SearchManager.SortDirection SortDirection {
            get {
                return this.SortDirectionField;
            }
            set {
                if ((this.SortDirectionField.Equals(value) != true)) {
                    this.SortDirectionField = value;
                    this.RaisePropertyChanged("SortDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public WIExample.SearchManager.SearchSorting Sorting {
            get {
                return this.SortingField;
            }
            set {
                if ((object.ReferenceEquals(this.SortingField, value) != true)) {
                    this.SortingField = value;
                    this.RaisePropertyChanged("Sorting");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchPaging", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class SearchPaging : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchSorting", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class SearchSorting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.SortBy SortByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortByAttributeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SortByDatasetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.SortDirection SortDirectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WIExample.SearchManager.SortBy SortBy {
            get {
                return this.SortByField;
            }
            set {
                if ((this.SortByField.Equals(value) != true)) {
                    this.SortByField = value;
                    this.RaisePropertyChanged("SortBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortByAttribute {
            get {
                return this.SortByAttributeField;
            }
            set {
                if ((object.ReferenceEquals(this.SortByAttributeField, value) != true)) {
                    this.SortByAttributeField = value;
                    this.RaisePropertyChanged("SortByAttribute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SortByDataset {
            get {
                return this.SortByDatasetField;
            }
            set {
                if ((this.SortByDatasetField.Equals(value) != true)) {
                    this.SortByDatasetField = value;
                    this.RaisePropertyChanged("SortByDataset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WIExample.SearchManager.SortDirection SortDirection {
            get {
                return this.SortDirectionField;
            }
            set {
                if ((this.SortDirectionField.Equals(value) != true)) {
                    this.SortDirectionField = value;
                    this.RaisePropertyChanged("SortDirection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchType", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    public enum SearchType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XML = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Object = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortDirection", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    public enum SortDirection : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ascending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Descending = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortBy", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    public enum SortBy : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ID = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Description = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attribute = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResult", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class SearchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TimeTakenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MoreRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TimeTaken {
            get {
                return this.TimeTakenField;
            }
            set {
                if ((this.TimeTakenField.Equals(value) != true)) {
                    this.TimeTakenField = value;
                    this.RaisePropertyChanged("TimeTaken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlResult {
            get {
                return this.XmlResultField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlResultField, value) != true)) {
                    this.XmlResultField = value;
                    this.RaisePropertyChanged("XmlResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int TotalRecordCount {
            get {
                return this.TotalRecordCountField;
            }
            set {
                if ((this.TotalRecordCountField.Equals(value) != true)) {
                    this.TotalRecordCountField = value;
                    this.RaisePropertyChanged("TotalRecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool MoreRecords {
            get {
                return this.MoreRecordsField;
            }
            set {
                if ((this.MoreRecordsField.Equals(value) != true)) {
                    this.MoreRecordsField = value;
                    this.RaisePropertyChanged("MoreRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class ServiceError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddTemplateMessage", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class AddTemplateMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.Template TemplateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WIExample.SearchManager.Template Template {
            get {
                return this.TemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateField, value) != true)) {
                    this.TemplateField = value;
                    this.RaisePropertyChanged("Template");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Template", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class Template : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.TemplateIdentifier IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WIExample.SearchManager.TemplateIdentifier ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Projection {
            get {
                return this.ProjectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectionField, value) != true)) {
                    this.ProjectionField = value;
                    this.RaisePropertyChanged("Projection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateIdentifier", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class TemplateIdentifier : WIExample.SearchManager.Identifier {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Identifier", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WIExample.SearchManager.ChangeIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WIExample.SearchManager.TemplateIdentifier))]
    public partial class Identifier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.Identifier ContextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WIExample.SearchManager.Identifier Context {
            get {
                return this.ContextField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextField, value) != true)) {
                    this.ContextField = value;
                    this.RaisePropertyChanged("Context");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeIdentifier", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class ChangeIdentifier : WIExample.SearchManager.Identifier {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateTemplateMessage", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class UpdateTemplateMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.Template TemplateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WIExample.SearchManager.Template Template {
            get {
                return this.TemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateField, value) != true)) {
                    this.TemplateField = value;
                    this.RaisePropertyChanged("Template");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteTemplateMessage", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class DeleteTemplateMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.Template TemplateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WIExample.SearchManager.Template Template {
            get {
                return this.TemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateField, value) != true)) {
                    this.TemplateField = value;
                    this.RaisePropertyChanged("Template");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchTemplateMessage", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class SearchTemplateMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.TemplateIdentifier IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CriteriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIExample.SearchManager.SearchOptions OptionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WIExample.SearchManager.TemplateIdentifier ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Criteria {
            get {
                return this.CriteriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CriteriaField, value) != true)) {
                    this.CriteriaField = value;
                    this.RaisePropertyChanged("Criteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public WIExample.SearchManager.SearchOptions Options {
            get {
                return this.OptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsField, value) != true)) {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.aveva.com/NET/2008/04/Contract", ConfigurationName="SearchManager.ISearchManager")]
    public interface ISearchManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/Search", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/SearchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SearchManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/SearchServiceErrorFault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        WIExample.SearchManager.SearchResult Search(string sessionKey, WIExample.SearchManager.SearchMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/AddTemplate", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/AddTemplateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SearchManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/AddTemplateServiceErrorF" +
            "ault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void AddTemplate(string sessionKey, WIExample.SearchManager.AddTemplateMessage addTemplateMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/UpdateTemplate", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/UpdateTemplateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SearchManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/UpdateTemplateServiceErr" +
            "orFault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void UpdateTemplate(string sessionKey, WIExample.SearchManager.UpdateTemplateMessage updateTemplateMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/DeleteTemplate", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/DeleteTemplateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SearchManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/DeleteTemplateServiceErr" +
            "orFault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void DeleteTemplate(string sessionKey, WIExample.SearchManager.DeleteTemplateMessage deleteTemplateMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/GetTemplate", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/GetTemplateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SearchManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/GetTemplateServiceErrorF" +
            "ault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        WIExample.SearchManager.Template GetTemplate(string sessionKey, WIExample.SearchManager.TemplateIdentifier templateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/GetTemplates", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/GetTemplatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SearchManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/GetTemplatesServiceError" +
            "Fault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        WIExample.SearchManager.Template[] GetTemplates(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/SearchUsingTemplate", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/SearchUsingTemplateRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SearchManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISearchManager/SearchUsingTemplateServi" +
            "ceErrorFault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        WIExample.SearchManager.SearchResult SearchUsingTemplate(string sessionKey, WIExample.SearchManager.SearchTemplateMessage searchMessageTemplate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchManagerChannel : WIExample.SearchManager.ISearchManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchManagerClient : System.ServiceModel.ClientBase<WIExample.SearchManager.ISearchManager>, WIExample.SearchManager.ISearchManager {
        
        public SearchManagerClient() {
        }
        
        public SearchManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WIExample.SearchManager.SearchResult Search(string sessionKey, WIExample.SearchManager.SearchMessage message) {
            return base.Channel.Search(sessionKey, message);
        }
        
        public void AddTemplate(string sessionKey, WIExample.SearchManager.AddTemplateMessage addTemplateMessage) {
            base.Channel.AddTemplate(sessionKey, addTemplateMessage);
        }
        
        public void UpdateTemplate(string sessionKey, WIExample.SearchManager.UpdateTemplateMessage updateTemplateMessage) {
            base.Channel.UpdateTemplate(sessionKey, updateTemplateMessage);
        }
        
        public void DeleteTemplate(string sessionKey, WIExample.SearchManager.DeleteTemplateMessage deleteTemplateMessage) {
            base.Channel.DeleteTemplate(sessionKey, deleteTemplateMessage);
        }
        
        public WIExample.SearchManager.Template GetTemplate(string sessionKey, WIExample.SearchManager.TemplateIdentifier templateID) {
            return base.Channel.GetTemplate(sessionKey, templateID);
        }
        
        public WIExample.SearchManager.Template[] GetTemplates(string sessionKey) {
            return base.Channel.GetTemplates(sessionKey);
        }
        
        public WIExample.SearchManager.SearchResult SearchUsingTemplate(string sessionKey, WIExample.SearchManager.SearchTemplateMessage searchMessageTemplate) {
            return base.Channel.SearchUsingTemplate(sessionKey, searchMessageTemplate);
        }
    }
}
