//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.296
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIExample {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WIExample.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CAD Asset.
        /// </summary>
        internal static string AssetViewButton {
            get {
                return ResourceManager.GetString("AssetViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open the link.
        /// </summary>
        internal static string AvevaDropDown {
            get {
                return ResourceManager.GetString("AvevaDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AVEVA.NET.
        /// </summary>
        internal static string AvevaItemContextMenu {
            get {
                return ResourceManager.GetString("AvevaItemContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AdminPOCNUC01.
        /// </summary>
        internal static string AvevaNetPassword {
            get {
                return ResourceManager.GetString("AvevaNetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FRPARPOCNUC01/Administrator.
        /// </summary>
        internal static string AvevaNetRole {
            get {
                return ResourceManager.GetString("AvevaNetRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ipetest.
        /// </summary>
        internal static string AvevaProject {
            get {
                return ResourceManager.GetString("AvevaProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C:\Program Files\Internet Explorer\iexplore.exe.
        /// </summary>
        internal static string IEPath {
            get {
                return ResourceManager.GetString("IEPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://frparpocnuc01:1111/default.aspx.
        /// </summary>
        internal static string LinkUrlToAvevaByID {
            get {
                return ResourceManager.GetString("LinkUrlToAvevaByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pressure: {0} bar.
        /// </summary>
        internal static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temperature: {0} °C\nPressure: {1} bar.
        /// </summary>
        internal static string ScadaLabel {
            get {
                return ResourceManager.GetString("ScadaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ScadaLabel.
        /// </summary>
        internal static string ScadaLabelGroup {
            get {
                return ResourceManager.GetString("ScadaLabelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sessionLAN.
        /// </summary>
        internal static string SessionManagerClient {
            get {
                return ResourceManager.GetString("SessionManagerClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temperature: {0} °C.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D:\CapGemini\iALM\VirtualReality\Dev\POC_WIPlugins\POC_WIPlugin_AssetDatasViewer\POC_WIPlugin_AssetDatasViewer\img\doc.png.
        /// </summary>
        internal static string TreeViewDocumentImage {
            get {
                return ResourceManager.GetString("TreeViewDocumentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à manager.
        /// </summary>
        internal static string WebServerPassword {
            get {
                return ResourceManager.GetString("WebServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrator.
        /// </summary>
        internal static string WebServerRole {
            get {
                return ResourceManager.GetString("WebServerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Admin.
        /// </summary>
        internal static string WebServerUsername {
            get {
                return ResourceManager.GetString("WebServerUsername", resourceCulture);
            }
        }
    }
}
