//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1008
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIExample.SessionManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionMessage", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class SessionMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSource {
            get {
                return this.DataSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSourceField, value) != true)) {
                    this.DataSourceField = value;
                    this.RaisePropertyChanged("DataSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class ServiceError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPropertyMessage", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class GetPropertyMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublicField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bag {
            get {
                return this.BagField;
            }
            set {
                if ((object.ReferenceEquals(this.BagField, value) != true)) {
                    this.BagField = value;
                    this.RaisePropertyChanged("Bag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Public {
            get {
                return this.PublicField;
            }
            set {
                if ((this.PublicField.Equals(value) != true)) {
                    this.PublicField = value;
                    this.RaisePropertyChanged("Public");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetPropertyMessage", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
    [System.SerializableAttribute()]
    public partial class SetPropertyMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bag {
            get {
                return this.BagField;
            }
            set {
                if ((object.ReferenceEquals(this.BagField, value) != true)) {
                    this.BagField = value;
                    this.RaisePropertyChanged("Bag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Public {
            get {
                return this.PublicField;
            }
            set {
                if ((this.PublicField.Equals(value) != true)) {
                    this.PublicField = value;
                    this.RaisePropertyChanged("Public");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.aveva.com/NET/2008/04/Contract", ConfigurationName="SessionManager.ISessionManager")]
    public interface ISessionManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/CreateSession", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/CreateSessionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SessionManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/CreateSessionServiceErr" +
            "orFault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        string CreateSession(WIExample.SessionManager.SessionMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/ReleaseSession", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/ReleaseSessionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SessionManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/ReleaseSessionServiceEr" +
            "rorFault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void ReleaseSession(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/LibraryVersion", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/LibraryVersionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SessionManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/LibraryVersionServiceEr" +
            "rorFault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        string LibraryVersion(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/GetProperty", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/GetPropertyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SessionManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/GetPropertyServiceError" +
            "Fault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        string GetProperty(string sessionKey, WIExample.SessionManager.GetPropertyMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/SetProperty", ReplyAction="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/SetPropertyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIExample.SessionManager.ServiceError), Action="http://www.aveva.com/NET/2008/04/Contract/ISessionManager/SetPropertyServiceError" +
            "Fault", Name="ServiceError", Namespace="http://schemas.aveva.com/NET/2008/04/Types")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void SetProperty(string sessionKey, WIExample.SessionManager.SetPropertyMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISessionManagerChannel : WIExample.SessionManager.ISessionManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionManagerClient : System.ServiceModel.ClientBase<WIExample.SessionManager.ISessionManager>, WIExample.SessionManager.ISessionManager {
        
        public SessionManagerClient() {
        }
        
        public SessionManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateSession(WIExample.SessionManager.SessionMessage message) {
            return base.Channel.CreateSession(message);
        }
        
        public void ReleaseSession(string sessionKey) {
            base.Channel.ReleaseSession(sessionKey);
        }
        
        public string LibraryVersion(string sessionKey) {
            return base.Channel.LibraryVersion(sessionKey);
        }
        
        public string GetProperty(string sessionKey, WIExample.SessionManager.GetPropertyMessage message) {
            return base.Channel.GetProperty(sessionKey, message);
        }
        
        public void SetProperty(string sessionKey, WIExample.SessionManager.SetPropertyMessage message) {
            base.Channel.SetProperty(sessionKey, message);
        }
    }
}
